//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetSubject()
        {
            this.AspNetAnnouncement_Subject = new HashSet<AspNetAnnouncement_Subject>();
            this.AspNetAssignments = new HashSet<AspNetAssignment>();
            this.AspNetAttendances = new HashSet<AspNetAttendance>();
            this.AspNetExams = new HashSet<AspNetExam>();
            this.AspNetStudent_Subject = new HashSet<AspNetStudent_Subject>();
            this.AspNetSubject_Curriculum = new HashSet<AspNetSubject_Curriculum>();
            this.AspNetTopics = new HashSet<AspNetTopic>();
            this.AspNetTests = new HashSet<AspNetTest>();
        }
    
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string TeacherID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAnnouncement_Subject> AspNetAnnouncement_Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAssignment> AspNetAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetAttendance> AspNetAttendances { get; set; }
        public virtual AspNetClass AspNetClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetExam> AspNetExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Subject> AspNetStudent_Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetSubject_Curriculum> AspNetSubject_Curriculum { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTopic> AspNetTopics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTest> AspNetTests { get; set; }
    }
}
