//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetSubject_Curriculum
    {
        public int Id { get; set; }
        public Nullable<int> WeightageValue { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<int> SubjectID { get; set; }
    
        public virtual AspNetCurriculum AspNetCurriculum { get; set; }
        public virtual AspNetSubject AspNetSubject { get; set; }
    }
}
