//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetSession()
        {
            this.AspNetTerms = new HashSet<AspNetTerm>();
        }
    
        public int Id { get; set; }
        public string SessionName { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> SessionStartDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> SessionEndDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetTerm> AspNetTerms { get; set; }
    }
}
