//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetTerm
    {
        public int Id { get; set; }
        public string TermName { get; set; }
        public Nullable<int> SessionID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> TermStartDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> TermEndDate { get; set; }
        public string Status { get; set; }
    
        public virtual AspNetSession AspNetSession { get; set; }
    }
}
