//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetExam()
        {
            this.AspNetStudent_Exam = new HashSet<AspNetStudent_Exam>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<double> Weightage { get; set; }
        public string TeacherID { get; set; }
    
        public virtual AspNetClass AspNetClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetStudent_Exam> AspNetStudent_Exam { get; set; }
        public virtual AspNetSubject AspNetSubject { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
