//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetStudent_Discount
    {
        public int Id { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> Percentage { get; set; }
    
        public virtual AspNetDiscountType AspNetDiscountType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
