//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEA_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Assignment
    {
        public int Id { get; set; }
        public string StudentID { get; set; }
        public int AssignmentID { get; set; }
        public string FileName { get; set; }
        public string SubmittedFileName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> MarksGot { get; set; }
    
        public virtual AspNetAssignment AspNetAssignment { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
